// <auto-generated />
using Barlangok.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Barlangok.Migrations
{
    [DbContext(typeof(BarlangDbContext))]
    [Migration("20250930065126_sqlite.local_migration_383")]
    partial class sqlitelocal_migration_383
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("Barlangok.Models.BarlangModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Hossz")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kiterjedes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Magassag")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Melyseg")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telepules")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Barlangok");
                });
#pragma warning restore 612, 618
        }
    }
}
